version: "3"
services:
  postgres:
    container_name: nestik_postgres
    image: postgres:latest
    ports:
      - "5435:5432"
    volumes:
      - /tmp/data/postgres:/tmp/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:nestik_postgres
    container_name: nestik_pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /tmp/data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge